name: CI Build & Deploy to Azure

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag para deploy manual'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: recipesapiregistry.azurecr.io
      IMAGE_NAME: recipes-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Definir tag para deploy
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Checkout na tag para deploy
        run: |
          git fetch --tags
          git checkout ${{ steps.set-tag.outputs.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: recipesapiregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            recipesapiregistry.azurecr.io/recipes-api:${{ steps.set-tag.outputs.tag }}

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v2
        with:
          app-name: recipes-api-app
          images: recipesapiregistry.azurecr.io/recipes-api:${{ steps.set-tag.outputs.tag }}